package com.ironhub.data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The Sailing boat-upgrade catalog (data/boat-upgrades.json, generated by
 * tools/gen_boat_upgrades.py from the Boat Upgrades hub plugin at its
 * pinned commit — BSD-2, IEarnSolo). Powers the Progression-hub "Sailing
 * upgrades" module.
 *
 * <p>Boat types: 0 = raft, 1 = skiff, 2 = sloop; -1 on a row = fits any
 * boat. Levels are boostable gates ({@code skillb:} — the reference itself
 * reads boosted levels); the ten late-game schematic gates ride in
 * {@code reqs} as {@code unlock:schematic_<slug>} flags the module mirrors
 * from the LOST_SCHEMATIC_* varbits. {@code detection.facilities} carries
 * the built-facility object ids seen on the player's own boat world
 * entity; core parts (base/hull/helm/sails/keel) read the sidepanel tier
 * varbits instead and have no object entries.</p>
 */
public class BoatUpgradesPack
{
	public int version;
	public String source;
	public List<Part> parts;
	public List<Upgrade> upgrades;
	public Detection detection;

	private transient Map<String, Part> byKey;
	private transient Map<Integer, FacilityHit> byObjectId;

	public Part part(String key)
	{
		if (byKey == null)
		{
			Map<String, Part> m = new HashMap<>();
			for (Part p : parts)
			{
				m.put(p.key, p);
			}
			byKey = m;
		}
		return byKey.get(key);
	}

	/** The facility part+tier a built-object id proves, or null. */
	public FacilityHit facilityByObjectId(int objectId)
	{
		if (byObjectId == null)
		{
			Map<Integer, FacilityHit> m = new HashMap<>();
			for (FacilityDetection d : detection.facilities)
			{
				for (Integer id : d.objectIds)
				{
					m.put(id, new FacilityHit(d.part, d.tier));
				}
			}
			byObjectId = m;
		}
		return byObjectId.get(objectId);
	}

	/** Rows of a part that fit the boat type, tier-ascending. */
	public List<Upgrade> rowsFor(String partKey, int boatType)
	{
		List<Upgrade> out = new ArrayList<>();
		for (Upgrade u : upgrades)
		{
			if (u.part.equals(partKey) && (u.boatType == -1 || u.boatType == boatType))
			{
				out.add(u);
			}
		}
		out.sort((a, b) -> Integer.compare(a.tier, b.tier));
		return out;
	}

	public static class Part
	{
		public String key;
		public String name;
		public String kind;      // core | facility
		public String benefit;
		public boolean raftExcluded;
	}

	public static class Upgrade
	{
		public String id;
		public String part;
		public int boatType;     // -1 any, 0 raft, 1 skiff, 2 sloop
		public int tier;
		public String name;
		public String page;      // wiki page title
		public int sailing;
		public int construction;
		public List<String> reqs;       // graph strings, allOf semantics
		public String schematic;        // display name, or null
		public List<Material> materials;
	}

	public static class Material
	{
		public String name;
		public int itemId;
		public int qty;
	}

	public static class Detection
	{
		public List<FacilityDetection> facilities;
		public List<Schematic> schematics;
	}

	public static class FacilityDetection
	{
		public String part;
		public int tier;
		public List<Integer> objectIds;
	}

	public static class Schematic
	{
		public String slug;
		public String name;
		public String upgrade;
		public int varbit;
	}

	/** A facility detection hit: which part, at which tier. */
	public static class FacilityHit
	{
		public final String part;
		public final int tier;

		public FacilityHit(String part, int tier)
		{
			this.part = part;
			this.tier = tier;
		}
	}
}
