package com.ironhub.data;

import java.util.List;
import java.util.Map;

/**
 * The Combat Profile's arithmetic (data/ca-profile.json, generated by
 * tools/gen_ca_profile.py from the pinned RuneStar cs2 dump). The
 * interface's seven profile rows are sums and maxima over player vars the
 * game hardcodes in script — nothing in the cache names them, so they are
 * projected here instead of guessed at runtime.
 */
public class CaProfilePack
{
	public String source;
	public String generated;
	/** The one boss index the game leaves out of its "Top X" scan. */
	public int excludedTopIndex;
	public List<Integer> tasksCompletedVarbits;
	public List<Integer> bossKillCountVarps;
	public List<Integer> skillingKillCountVarps;
	public List<Integer> raidCompletionVarps;
	/** Boss index → the varp(s) holding its kill count (one boss sums six). */
	public Map<String, List<Integer>> killVarps;

	/** The varps a boss index's kill count is read from; empty when the dump
	 *  does not map it (a boss added since the pin) — the caller shows no
	 *  count rather than a zero it cannot vouch for. */
	public List<Integer> killVarpsFor(int bossIndex)
	{
		List<Integer> varps = killVarps.get(String.valueOf(bossIndex));
		return varps == null ? List.of() : varps;
	}

	public boolean hasKillCount(int bossIndex)
	{
		return !killVarpsFor(bossIndex).isEmpty();
	}
}
