package com.ironhub.data;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Collection-log activities, drop rates and slots (data/clog.json,
 * generated by tools/gen_clog.py from the Log Adviser plugin's tables —
 * github.com/SFranciscoSouza/LogAdviser, BSD-2-Clause). Rates are the
 * IRONMAN completions/hr; requirement strings are in the shared
 * requirement-graph {@code parse()} form.
 */
public class ClogPack
{
	public String source;
	public String generated;
	public List<Activity> activities;
	public List<Slot> slots;
	public List<Alias> aliases;
	public List<ChatName> chatNames;

	private transient volatile Map<Integer, Integer> canonicalByAlt;
	private transient volatile Set<Integer> slotIds;
	private transient volatile Map<String, Integer> idsByName;

	/** The canonical slot item id for an item (body-type variants map to
	 *  the id slots.json carries), or the id unchanged. */
	public int canonical(int itemId)
	{
		if (canonicalByAlt == null)
		{
			Map<Integer, Integer> m = new HashMap<>();
			for (Alias a : aliases)
			{
				m.put(a.alt, a.canonical);
			}
			canonicalByAlt = m;
		}
		return canonicalByAlt.getOrDefault(itemId, itemId);
	}

	/** Canonical item ids of every known log slot. */
	public Set<Integer> slotIds()
	{
		if (slotIds == null)
		{
			Set<Integer> ids = new HashSet<>();
			for (Slot s : slots)
			{
				ids.add(s.itemId);
			}
			slotIds = ids;
		}
		return slotIds;
	}

	/** Lowercased slot name -> canonical item id (chat-message resolution),
	 *  including the chat-only aliases. Null when the name is unknown. */
	public Integer itemIdByName(String name)
	{
		if (idsByName == null)
		{
			Map<String, Integer> m = new HashMap<>();
			for (Slot s : slots)
			{
				m.put(s.name.toLowerCase(Locale.ROOT), s.itemId);
			}
			for (ChatName c : chatNames)
			{
				m.put(c.name.toLowerCase(Locale.ROOT), c.itemId);
			}
			idsByName = m;
		}
		return idsByName.get(name.toLowerCase(Locale.ROOT));
	}

	public static class Activity
	{
		public int index;
		public String name;
		public double perHour;
		public double extraTimeFirst;
		public String category;
		public List<String> reqs;
		public List<Item> items;
	}

	public static class Item
	{
		public int itemId;
		public String name;
		public boolean requiresPrevious;
		public boolean exact;
		public boolean independent;
		public double attempts;
	}

	public static class Slot
	{
		public int itemId;
		public String name;
	}

	public static class Alias
	{
		public int alt;
		public int canonical;
	}

	public static class ChatName
	{
		public String name;
		public int itemId;
	}
}
