package com.ironhub.data;

import java.util.List;

/**
 * The collection log's ranks (data/clog-ranks.json, generated by
 * tools/gen_clog_ranks.py from the wiki's Collection log article): fill
 * enough slots and The Collector hands over the matching staff of
 * collection. The overview frames your count between the rank you have
 * reached and the one you are climbing to, each shown by its staff.
 */
public class ClogRanksPack
{
	public String source;
	public String generated;
	/** The article's stated slot total when the pack was generated. */
	public int totalSlots;
	public List<Rank> ranks;

	public static class Rank
	{
		public String name;
		public int slots;
		public int itemId;
		/** Gilded's threshold is a share of the log's total, so it moves with
		 *  every update: present = recompute from the live total. */
		public Double percentOfTotal;
		public Integer roundDown;
	}

	/**
	 * A rank's threshold against the player's live slot total — a share-based
	 * rank (Gilded) recomputes, so a game update that adds slots never leaves
	 * us quoting a stale number.
	 */
	public int threshold(Rank rank, int liveTotal)
	{
		if (rank.percentOfTotal == null || liveTotal <= 0)
		{
			return rank.slots;
		}
		int step = rank.roundDown == null || rank.roundDown < 1 ? 1 : rank.roundDown;
		return (int) (liveTotal * rank.percentOfTotal) / step * step;
	}

	/** The highest rank the player has reached, or null below the first. */
	public Rank reached(int slots, int liveTotal)
	{
		Rank best = null;
		for (Rank rank : ranks)
		{
			if (slots >= threshold(rank, liveTotal))
			{
				best = rank;
			}
		}
		return best;
	}

	/** The rank being climbed to, or null once every rank is claimed. */
	public Rank next(int slots, int liveTotal)
	{
		for (Rank rank : ranks)
		{
			if (slots < threshold(rank, liveTotal))
			{
				return rank;
			}
		}
		return null;
	}

	/** A rank's 1-based place in the ladder — the game's "VII: Rune". */
	public int number(Rank rank)
	{
		return rank == null ? 0 : ranks.indexOf(rank) + 1;
	}

	private static final String[] NUMERALS = {
		"I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII"};

	/** "VII: Rune", the game's own label; "" for no rank. */
	public String label(Rank rank)
	{
		int number = number(rank);
		if (number < 1)
		{
			return "";
		}
		String numeral = number <= NUMERALS.length ? NUMERALS[number - 1]
			: String.valueOf(number);
		return numeral + ": " + rank.name;
	}
}
