package com.ironhub.data;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.runelite.api.coords.WorldPoint;

/**
 * Emote clue steps + STASH units (data/clue-steps.json, generated by
 * tools/gen_clue_steps.py): every emote clue from core's cluescrolls
 * plugin — tier, text, world point, item requirements as graph strings
 * (allOf semantics; {@code any:} composites for alternatives, variants
 * counted by the {@code item:} leaves) — and every STASH unit with its
 * tier, built-object id and linked clue (from the STASH Tracker plugin's
 * unit table, BSD-2, github.com/Nearvaas/S.T.A.S.H-Toolkit).
 */
public class ClueStepsPack
{
	public int version;
	public List<Clue> clues;
	public List<Stash> stash;

	private transient volatile Map<String, Clue> clueById;
	private transient volatile Map<Integer, Stash> stashByObject;

	public Clue clue(String id)
	{
		if (clueById == null)
		{
			Map<String, Clue> m = new HashMap<>();
			for (Clue c : clues)
			{
				m.put(c.id, c);
			}
			clueById = m;
		}
		return clueById.get(id);
	}

	/** The STASH unit whose built game object has this id, or null. */
	public Stash stashByObjectId(int objectId)
	{
		if (stashByObject == null)
		{
			Map<Integer, Stash> m = new HashMap<>();
			for (Stash s : stash)
			{
				m.put(s.objectId, s);
			}
			stashByObject = m;
		}
		return stashByObject.get(objectId);
	}

	public static class Clue
	{
		public String id;
		public String tier;
		public String text;
		public String area;
		public int x;
		public int y;
		public int plane;
		/** Requirement-graph strings, allOf semantics (empty = no items needed). */
		public List<String> reqs;
		/** True when the step demands empty equipment slot(s) — alone
		 *  ("nothing equipped") or alongside item requirements ("no jewelry"). */
		public Boolean nothing;
		/** STASH unit key when this step has one. */
		public String stash;

		public WorldPoint worldPoint()
		{
			return new WorldPoint(x, y, plane);
		}
	}

	public static class Stash
	{
		public String key;
		public String tier;
		public int objectId;
		public String name;
		public int x;
		public int y;
		public int plane;
		/** The emote clue whose outfit this unit stores (null: no core clue). */
		public String clueId;

		public WorldPoint worldPoint()
		{
			return new WorldPoint(x, y, plane);
		}
	}
}
