package com.ironhub.data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.runelite.api.coords.WorldPoint;

/**
 * Repeatable events and the guided run over them (data/dailies.json,
 * generated by tools/gen_dailies.py from the OSRS wiki's Repeatable events
 * page joined to RuneLite's core Daily Task Indicator varbits).
 *
 * <p>Only events a standard ironman can actually travel to are in the pack:
 * the NMZ herb boxes are ironman-blocked by the game itself, and the pure
 * charge/perk dailies (cape and ring charges, resurrections) are excluded
 * because they are used where you already are, not routed to.
 */
public class DailiesPack
{
	public String source;
	public String generated;
	/** Every event, in the run's route order. */
	public List<Daily> dailies;

	private transient Map<String, Daily> byId;

	public Daily daily(String id)
	{
		if (byId == null)
		{
			Map<String, Daily> m = new HashMap<>();
			for (Daily daily : dailies)
			{
				m.put(daily.id, daily);
			}
			byId = m;
		}
		return byId.get(id);
	}

	/** Ordered ids — the run's route. */
	public List<String> route()
	{
		List<String> ids = new ArrayList<>();
		for (Daily daily : dailies)
		{
			ids.add(daily.id);
		}
		return ids;
	}

	public static class Daily
	{
		public String id;
		/** Row label, e.g. "Battlestaves from Zaff". */
		public String name;
		/** Where it happens, e.g. "Zaff, Varrock" — the wiki's own wording. */
		public String where;
		/** "daily" (00:00 UTC) or "rolling7" (7 days from your last visit). */
		public String reset;
		public Point point;
		/** Requirement-graph strings gating access (empty = always open). */
		public List<String> reqs;
		public Detection detection;
		/** Amount received per diary tier, smallest first; best met wins. */
		public List<Tier> tiers;
		/** What to bring, scaled off the tier you qualify for (13 bones, 250
		 *  noted flax, 840k coins). Display only — we tell you, we don't gate. */
		public List<Bring> bring;
		/** How players get there, in the wiki's own words ("Camelot teleport").
		 *  A hint beside the stop; Shortest Path does the actual routing. */
		public String travel;
		/** One honest sentence of context, or null. */
		public String note;

		public WorldPoint worldPoint()
		{
			return new WorldPoint(point.x, point.y, point.plane);
		}
	}

	/**
	 * How we know it has been claimed.
	 * <ul>
	 *   <li>{@code flag} — varbit reads 0 while unclaimed (core's semantics);</li>
	 *   <li>{@code count} — varbit counts what you have taken, capped by tier;</li>
	 *   <li>{@code rolling7} — no claim varbit exists; {@code varbit} is instead
	 *       the live "you are doing it now" signal that stamps the visit;</li>
	 *   <li>{@code manual} — the game exposes no flag at all; hand-ticked.</li>
	 * </ul>
	 */
	public static class Detection
	{
		public String mode;
		public int varbit;
		/** A game message that means "this is claimable now", matched as a
		 *  substring so colour tags cannot break it. Null for most events —
		 *  only Tears of Guthix announces itself. */
		public String chat;
	}

	public static class Tier
	{
		/** Requirement-graph string, or null for the no-diary base amount. */
		public String req;
		public int qty;
	}

	public static class Point
	{
		public int x;
		public int y;
		public int plane;
	}

	/** A thing to bring. {@code per} is the amount needed for each unit you
	 *  collect (7,000 coins per battlestaff, 1 bone per bonemeal), so the
	 *  total tracks whichever diary tier you have. */
	public static class Bring
	{
		public String label;
		public int per;
	}
}
