package com.ironhub.data;

import java.util.List;

/**
 * Achievement diary data pack (data/diaries.json): every task's official
 * journal text, completion flag (varplayer bit, or varbit + minimum for
 * Karamja), wiki requirements, and per-tier rewards. Generated by
 * tools/gen_diaries.py from the OSRS wiki diary pages joined with Quest
 * Helper's task flag mappings — never hand-edit.
 */
public class DiariesPack
{
	public String source;
	public String generated;
	public List<Region> regions;

	public static class Region
	{
		public String name;
		public List<Tier> tiers;
	}

	public static class Tier
	{
		public String tier;
		public List<Task> tasks;
		public List<String> rewards;
	}

	public static class Task
	{
		public String task;
		public String note;
		/** Varplayer holding this task's completion bit (all regions but Karamja). */
		public Integer varp;
		public Integer bit;
		/** Karamja: per-task varbit, complete once its value reaches {@link #min}. */
		public Integer varbit;
		public Integer min;
		public List<Req> reqs;
	}

	/** One requirement line; {@code req} is present when it parses into the
	 * requirement graph (skillb:/quest: leaf), otherwise display-only. */
	public static class Req
	{
		public String text;
		public String req;
	}
}
