package com.ironhub.data;

import java.util.List;

/**
 * Every wearable in the game (data/equipment.json, generated by
 * tools/gen_equipment.py from knowledge.db): slot, combat stats, members
 * and a value, for the Gear library. Obtainment and equip requirements are
 * NOT here — those live in {@link ItemSourcesPack}, which the library reads
 * by id so the two never disagree.
 */
public class EquipmentPack
{
	public String source;
	public String generated;
	/** The 14 stat names, in the order {@link Item#stats} holds them. */
	public List<String> statKeys;
	public List<Item> items;

	/** Stat indices into {@link Item#stats}, matching statKeys. */
	public static final int A_STAB = 0;
	public static final int A_SLASH = 1;
	public static final int A_CRUSH = 2;
	public static final int A_RANGE = 3;
	public static final int A_MAGIC = 4;
	public static final int D_STAB = 5;
	public static final int D_SLASH = 6;
	public static final int D_CRUSH = 7;
	public static final int D_RANGE = 8;
	public static final int D_MAGIC = 9;
	public static final int STR = 10;
	public static final int RSTR = 11;
	public static final int MDMG = 12;
	public static final int PRAYER = 13;

	public static class Item
	{
		public String name;
		public String slot;
		public int[] ids;
		public boolean members;
		/** The 14 combat bonuses (statKeys order). */
		public int[] stats;
		/** Weapon attack speed in ticks; 0 = not a weapon / no speed. */
		public int speed;
		/** GE guide price, 0 = untradeable / unknown. */
		public int ge;
		/** High-alchemy value, 0 = unknown. */
		public int alch;

		/** The value to sort and show: GE price where tradeable, else alch. */
		public int value()
		{
			return ge > 0 ? ge : alch;
		}

		/** The canonical (first) item id — the sprite and ownership key. */
		public int primaryId()
		{
			return ids != null && ids.length > 0 ? ids[0] : 0;
		}
	}
}
