package com.ironhub.data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.runelite.api.coords.WorldPoint;

/**
 * Farm-run stops and their teleport options (data/farm-runs.json,
 * generated by tools/gen_farm_runs.py from the Easy Farming plugin's
 * location tables — github.com/Speaax/Farming-Helper, BSD-2-Clause).
 * Locations are in the source plugin's route order per category; which
 * patches actually exist at a stop is resolved live from the vendored
 * FarmingWorld by the stop's region, never trusted from here.
 */
public class FarmRunsPack
{
	public String source;
	public String generated;
	public List<Location> locations;

	private transient Map<String, Location> byId;

	public Location location(String id)
	{
		if (byId == null)
		{
			Map<String, Location> m = new HashMap<>();
			for (Location location : locations)
			{
				m.put(location.id, location);
			}
			byId = m;
		}
		return byId.get(id);
	}

	/** Locations of one category, in route order. */
	public List<Location> category(String category)
	{
		List<Location> out = new ArrayList<>();
		for (Location location : locations)
		{
			if (location.category.equals(category))
			{
				out.add(location);
			}
		}
		return out;
	}

	public static class Location
	{
		public String id;
		public String category;
		public String name;
		public Point point;
		public List<Teleport> teleports;

		public WorldPoint worldPoint()
		{
			return new WorldPoint(point.x, point.y, point.plane);
		}
	}

	public static class Point
	{
		public int x;
		public int y;
		public int plane;
	}

	public static class Teleport
	{
		public String id;
		public String category;
		public String description;
		public String supplier; // "house" / "fairyRing" — access-based, no item check
		public List<Item> items;
	}

	public static class Item
	{
		public int itemId;
		public int qty;
	}
}
