package com.ironhub.data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.runelite.api.coords.WorldPoint;

/**
 * Hunters' Rumours pack (data/hunter-rumours.json, generated by
 * tools/gen_hunter_rumours.py from the Hunter Rumours plugin — BSD-2,
 * geel9/DapperMickie): the six Guild Hunters and their tiers, every
 * rumour target (trap, pity thresholds bare/full-outfit, Hunter level,
 * the creature's possible Hunter-xp drops = the catch-counting signal,
 * and which tiers assign it), the hunting-location areas with fairy ring
 * codes, and the Guild hunter outfit piece ids.
 */
public class HunterRumoursPack
{
	public int version;
	public List<Hunter> hunters;
	public List<Rumour> rumours;
	public List<Location> locations;
	public List<Integer> outfit;

	private transient volatile Map<Integer, Hunter> hunterByNpc;
	private transient volatile Map<String, Rumour> rumourById;

	public Hunter hunterByNpcId(int npcId)
	{
		if (hunterByNpc == null)
		{
			Map<Integer, Hunter> m = new HashMap<>();
			for (Hunter h : hunters)
			{
				m.put(h.npcId, h);
			}
			hunterByNpc = m;
		}
		return hunterByNpc.get(npcId);
	}

	/** Hunter whose in-game NPC name matches (case-insensitive), or null. */
	public Hunter hunterByNpcName(String npcName)
	{
		if (npcName == null)
		{
			return null;
		}
		for (Hunter h : hunters)
		{
			if (h.npcName.equalsIgnoreCase(npcName))
			{
				return h;
			}
		}
		return null;
	}

	/** First hunter whose common name appears in the text, or null. */
	public Hunter hunterReferenced(String lowerText)
	{
		for (Hunter h : hunters)
		{
			if (lowerText.contains(h.name.toLowerCase()))
			{
				return h;
			}
		}
		return null;
	}

	public Rumour rumour(String id)
	{
		if (rumourById == null)
		{
			Map<String, Rumour> m = new HashMap<>();
			for (Rumour r : rumours)
			{
				m.put(r.id, r);
			}
			rumourById = m;
		}
		return id == null ? null : rumourById.get(id);
	}

	/** First rumour whose display name appears in the text, or null. */
	public Rumour rumourReferenced(String lowerText)
	{
		for (Rumour r : rumours)
		{
			if (lowerText.contains(r.name.toLowerCase()))
			{
				return r;
			}
		}
		return null;
	}

	/** Location areas for a creature, in pack order. */
	public List<Location> locationsFor(String creature)
	{
		List<Location> out = new ArrayList<>();
		for (Location l : locations)
		{
			if (l.creature.equals(creature))
			{
				out.add(l);
			}
		}
		return out;
	}

	public static class Hunter
	{
		public String id;
		public int npcId;
		public String name;     // common name (Wolf, Teco, …)
		public String npcName;  // full NPC name (Guild Hunter Wolf)
		public String tier;
	}

	public static class Rumour
	{
		public String id;
		public String name;
		public String creature;    // Creature enum constant
		public int npcId;          // target creature NPC id (0 unknown)
		public int icon;           // creature item sprite
		public int pieceItemId;    // the rare "piece" turned in
		public String trap;
		public int trapItemId;
		public String trapItemName;
		public int pity;           // guaranteed-piece threshold, no outfit
		public int pityWithOutfit; // ... with full guild hunter outfit
		public int level;
		public List<String> reqs;  // skillb:Hunter:<level>
		public List<String> tiers; // assigning tiers
		public List<Integer> xpDrops; // Hunter xp per catch (empty when a range)
		public List<Integer> xpRange; // [lo, hi] for herbiboar

		/** Whether a Hunter-xp gain matches a catch of this creature. */
		public boolean matchesCatchXp(int xp)
		{
			if (xpRange != null && xpRange.size() == 2)
			{
				return xp >= xpRange.get(0) && xp <= xpRange.get(1);
			}
			return xpDrops != null && xpDrops.contains(xp);
		}

		/** Guaranteed-piece threshold given owned outfit pieces (0–4),
		 *  linearly interpolated as the plugin does. */
		public int pityFor(int outfitPieces)
		{
			int diff = pity - pityWithOutfit;
			double perItem = diff / 4d * Math.max(0, Math.min(4, outfitPieces));
			return (int) Math.floor(pity - perItem);
		}
	}

	public static class Location
	{
		public String creature;
		public String name;
		public int x;
		public int y;
		public int plane;
		public String fairyRing; // 3-letter code, or null
		public int spots;        // number of trap spots in the area

		public WorldPoint worldPoint()
		{
			return new WorldPoint(x, y, plane);
		}
	}
}
