package com.ironhub.data;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.Map;

/**
 * Offline item name → id index ({@code data/index/item-names.json},
 * generated by tools/gen_item_names.py from the pinned API's ItemID
 * constants — which are themselves normalized cache names, so wiki item
 * names normalize straight onto them). Covers untradeables, which the
 * client's price-list search does not.
 */
public class ItemNameIndex
{
	private final Map<String, Integer> byNormalizedName;

	public ItemNameIndex(Gson gson)
	{
		InputStream in = ItemNameIndex.class.getResourceAsStream("/data/index/item-names.json");
		if (in == null)
		{
			throw new IllegalStateException("missing item name index");
		}
		try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8))
		{
			byNormalizedName = gson.fromJson(reader, new TypeToken<Map<String, Integer>>()
			{
			}.getType());
		}
		catch (Exception e)
		{
			throw new IllegalStateException("corrupt item name index", e);
		}
	}

	/** Item id for a display name ("Slayer helmet (i)"), or null. */
	public Integer idOf(String name)
	{
		return byNormalizedName.get(normalize(name));
	}

	/** Display-name search: names containing the query, best-effort order. */
	public java.util.List<String> search(String query, int limit)
	{
		String needle = normalize(query);
		// sort the NORMALIZED keys (they are the match domain anyway) \u2014 the
		// old comparator re-ran normalize()'s three regex passes on every
		// comparison, per keystroke on the EDT (2026-07-20 audit)
		java.util.List<String> hits = new java.util.ArrayList<>();
		for (String key : byNormalizedName.keySet())
		{
			if (key.contains(needle))
			{
				hits.add(key);
				if (hits.size() >= limit * 4)
				{
					break;
				}
			}
		}
		hits.sort(java.util.Comparator
			.comparing((String key) -> !key.startsWith(needle))
			.thenComparing(String::length));
		java.util.List<String> out = new java.util.ArrayList<>();
		for (int i = 0; i < Math.min(limit, hits.size()); i++)
		{
			out.add(pretty(hits.get(i)));
		}
		return out;
	}

	// compiled once \u2014 normalize runs per keystroke and per idOf lookup
	private static final java.util.regex.Pattern APOSTROPHES =
		java.util.regex.Pattern.compile("['\u2019]");
	private static final java.util.regex.Pattern NON_ALNUM =
		java.util.regex.Pattern.compile("[^A-Z0-9]+");
	private static final java.util.regex.Pattern EDGE_UNDERSCORES =
		java.util.regex.Pattern.compile("^_|_$");

	static String normalize(String name)
	{
		// apostrophes vanish in ItemID constants (AHRIMS_ROBETOP), they
		// don't become separators
		String s = APOSTROPHES.matcher(name).replaceAll("");
		s = NON_ALNUM.matcher(s.toUpperCase(Locale.ROOT)).replaceAll("_");
		return EDGE_UNDERSCORES.matcher(s).replaceAll("");
	}

	private static String pretty(String normalized)
	{
		String lower = normalized.toLowerCase(Locale.ROOT).replace('_', ' ');
		return Character.toUpperCase(lower.charAt(0)) + lower.substring(1);
	}
}
