package com.ironhub.data;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.Map;

/**
 * Offline item name → id index ({@code data/index/item-names.json},
 * generated by tools/gen_item_names.py from the pinned API's ItemID
 * constants — which are themselves normalized cache names, so wiki item
 * names normalize straight onto them). Covers untradeables, which the
 * client's price-list search does not.
 */
public class ItemNameIndex
{
	private final Map<String, Integer> byNormalizedName;

	public ItemNameIndex(Gson gson)
	{
		InputStream in = ItemNameIndex.class.getResourceAsStream("/data/index/item-names.json");
		if (in == null)
		{
			throw new IllegalStateException("missing item name index");
		}
		try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8))
		{
			byNormalizedName = gson.fromJson(reader, new TypeToken<Map<String, Integer>>()
			{
			}.getType());
		}
		catch (Exception e)
		{
			throw new IllegalStateException("corrupt item name index", e);
		}
	}

	/** Item id for a display name ("Slayer helmet (i)"), or null. */
	public Integer idOf(String name)
	{
		return byNormalizedName.get(normalize(name));
	}

	/** Display-name search: names containing the query, best-effort order. */
	public java.util.List<String> search(String query, int limit)
	{
		String needle = normalize(query);
		java.util.List<String> hits = new java.util.ArrayList<>();
		for (String key : byNormalizedName.keySet())
		{
			if (key.contains(needle))
			{
				hits.add(pretty(key));
				if (hits.size() >= limit * 4)
				{
					break;
				}
			}
		}
		hits.sort(java.util.Comparator
			.comparing((String s) -> !normalize(s).startsWith(needle))
			.thenComparing(String::length));
		return hits.subList(0, Math.min(limit, hits.size()));
	}

	static String normalize(String name)
	{
		return name.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]+", "_")
			.replaceAll("^_|_$", "");
	}

	private static String pretty(String normalized)
	{
		String lower = normalized.toLowerCase(Locale.ROOT).replace('_', ' ');
		return Character.toUpperCase(lower.charAt(0)) + lower.substring(1);
	}
}
