package com.ironhub.data;

import java.util.List;

/**
 * The OSRS wiki Money making guide (data/money-making.json, generated by
 * tools/gen_money_making.py). Powers the Bank-section "Money making" module.
 *
 * <p>{@code reqs} are the HARD requirements (graph strings — skill/quest/combat
 * gates) that decide availability; {@code recommends} are soft (combat levels,
 * recommended gear/levels) that inform readiness but never block. {@code profit}
 * is an hourly-gp GE-price SNAPSHOT (regenerate to refresh); recurring methods
 * carry {@code time} + per-run profit instead of gp/hr.
 */
public class MoneyMakingPack
{
	public String source;
	public String generated;
	public String gePricesAsOf;
	public int version;
	public List<Method> methods;

	public static class Method
	{
		public String id;
		public String name;
		public String category;   // Collecting/Combat/Processing/Skilling/Recurring/Other
		public String intensity;  // Low/Moderate/High (blank for recurring)
		public boolean members;
		public boolean recurring;
		public Integer profit;     // hourly gp, or per-run for recurring; null unknown
		public String time;        // recurring only: time per run
		public String wiki;        // wiki page path
		public int icon;           // representative item id (0 = none)
		public List<String> reqs;        // hard requirement graph strings
		public List<String> recommends;  // soft recommendation graph strings
		public List<Input> inputs;       // supplies/materials consumed
		public List<Input> outputs;      // items produced (incl. combat drops)
		public String skillsText;
		public String itemsText;
		public String otherText;
	}

	public static class Input
	{
		public String name;
		public int itemId;   // 0 when unresolved (e.g. Coins)
		public String qty;   // raw (may be "3", "1/6", "10000 / 8" …)
		public boolean perHour;
	}
}
