package com.ironhub.data;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Useful POH progression (data/poh.json, generated by tools/gen_poh.py):
 * the spaces worth building per the wiki's POH progression guide, each a
 * ladder of tiers with the Construction level (boostable — skillb:),
 * curated quest/item gates, the built furniture's object ids (every
 * decoration/state variant — the in-own-house detection signal) and item
 * icons for tiles.
 */
public class PohPack
{
	public int version;
	public List<Space> spaces;

	private transient Map<Integer, Tier> byObjectId;

	/** The tier whose built furniture has this object id, or null. */
	public Tier tierByObjectId(int objectId)
	{
		if (byObjectId == null)
		{
			Map<Integer, Tier> m = new HashMap<>();
			for (Space space : spaces)
			{
				for (Tier tier : space.tiers)
				{
					for (Integer id : tier.objectIds)
					{
						m.put(id, tier);
					}
				}
			}
			byObjectId = m;
		}
		return byObjectId.get(objectId);
	}

	public static class Space
	{
		public String id;
		public String name;
		public String room;
		public Integer icon;
		/** Build-progression order; the first unbuilt tier is "next". */
		public List<Tier> tiers;
	}

	public static class Tier
	{
		public String id;    // <space>:<slug> — the persisted built-mark key
		public String name;
		public String page;  // wiki page title
		public int level;
		/** Requirement-graph strings, allOf semantics (skillb Construction + gates). */
		public List<String> reqs;
		public List<Integer> objectIds;
		public Integer icon;
	}
}
