package com.ironhub.data;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The complete POH catalog (data/poh.json, generated by tools/gen_poh.py):
 * every buildable room, its hotspots, and each hotspot's ladder of furniture
 * with the Construction level (boostable — skillb:), build materials, the
 * built furniture's object ids (every decoration/state variant — the
 * in-own-house detection signal) and item icons for tiles.
 */
public class PohPack
{
	public int version;
	public List<Space> spaces;
	/** The game's unbuilt-hotspot marker objects — what the scene itself shows
	 *  while the player is editing the house. Never buildable furniture. */
	public List<Integer> buildModeMarkers = List.of();

	private transient volatile Map<Integer, List<Placement>> byObjectId;
	private transient volatile java.util.Set<Integer> markerIds;

	/** Whether this object id is one of the game's build-mode hotspot markers. */
	public boolean isBuildModeMarker(int objectId)
	{
		java.util.Set<Integer> local = markerIds;
		if (local == null)
		{
			markerIds = local = new java.util.HashSet<>(buildModeMarkers);
		}
		return local.contains(objectId);
	}

	/** One place a furniture can be built: the hotspot (with its room) and the
	 *  tier itself. The same furniture — a rug, a fireplace — is buildable in
	 *  several rooms, so one object id can have several placements. */
	public static final class Placement
	{
		public final Space space;
		public final Tier tier;

		Placement(Space space, Tier tier)
		{
			this.space = space;
			this.tier = tier;
		}
	}

	/**
	 * Every place this built-object id could be, never null. More than one
	 * means the game uses the identical object in several rooms' hotspots
	 * (the 146 shared ids), so the caller must disambiguate — PohModule does
	 * it by which house room the object spawned in.
	 */
	public List<Placement> placementsByObjectId(int objectId)
	{
		Map<Integer, List<Placement>> local = byObjectId;
		if (local == null)
		{
			local = new HashMap<>();
			for (Space space : spaces)
			{
				for (Tier tier : space.tiers)
				{
					for (Integer id : tier.objectIds)
					{
						local.computeIfAbsent(id, k -> new java.util.ArrayList<>())
							.add(new Placement(space, tier));
					}
				}
			}
			byObjectId = local;
		}
		return local.getOrDefault(objectId, List.of());
	}

	public static class Space
	{
		public String id;
		public String name;
		public String room;
		public Integer icon;
		/** What the hotspot does for the player (from the top tier's wiki
		 *  intro); null for a purely cosmetic hotspot. */
		public String benefit;
		/** Build-progression order; the first unbuilt tier is "next". */
		public List<Tier> tiers;
	}

	public static class Tier
	{
		public String id;    // <space>:<slug> — the persisted built-mark key
		public String name;
		public String page;  // wiki page title
		public int level;
		/** Requirement-graph strings, allOf semantics (skillb Construction + gates). */
		public List<String> reqs;
		public List<Integer> objectIds;
		public Integer icon;
		/** The tier's {{Recipe}} build materials (v2) — may be empty. */
		public List<Material> materials = List.of();
	}

	public static class Material
	{
		public int itemId;
		public String name;
		public int qty;
	}
}
