package com.ironhub.data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.PriorityQueue;

/**
 * Sailing port-task static tables (data/port-tasks.json, generated by
 * tools/gen_port_tasks.py from the Port Tasks hub plugin at its pinned
 * commit — BSD-2, nucleon + Cooper Morris). The task CATALOG itself is
 * runtime data (cache DBTable 197); this pack carries what the game does
 * not expose: per-task Sailing XP (transcribed by the reference authors,
 * keyed by DBRow), the 30 ports, and per-pair sailing distances in tiles
 * (the reference's route polylines reduced to their lengths).
 *
 * <p>{@link #distance} answers any port pair: direct route length when
 * one exists, else the shortest chain of known routes (Dijkstra over the
 * route graph — sea travel is port-to-port), NaN only if a port is
 * unknown.</p>
 */
public class PortTasksPack
{
	public int version;
	public String source;
	public List<Port> ports;
	public List<Reward> rewards;
	public List<Route> routes;

	private transient volatile Map<Integer, Port> portByDbrow;
	private transient volatile Map<Integer, Reward> rewardByDbrow;
	/** Growing Dijkstra cache, hit from the EDT tab and the client render
	 *  thread — ConcurrentHashMap, values immutable once stored
	 *  (2026-07-20 audit: was a plain HashMap mutated unsynchronized). */
	private final transient Map<Integer, Map<Integer, Double>> shortest =
		new java.util.concurrent.ConcurrentHashMap<>();

	public Port port(int dbrow)
	{
		if (portByDbrow == null)
		{
			Map<Integer, Port> m = new HashMap<>();
			for (Port p : ports)
			{
				m.put(p.dbrow, p);
			}
			portByDbrow = m;
		}
		return portByDbrow.get(dbrow);
	}

	public Reward reward(int dbrow)
	{
		if (rewardByDbrow == null)
		{
			Map<Integer, Reward> m = new HashMap<>();
			for (Reward r : rewards)
			{
				m.put(r.dbrow, r);
			}
			rewardByDbrow = m;
		}
		return rewardByDbrow.get(dbrow);
	}

	/** Sailing distance in tiles between two ports (0 for the same port);
	 *  NaN when either port is unknown. */
	public double distance(int fromDbrow, int toDbrow)
	{
		if (fromDbrow == toDbrow)
		{
			return 0;
		}
		Map<Integer, Double> row = shortestFrom(fromDbrow);
		if (row == null)
		{
			return Double.NaN;
		}
		Double d = row.get(toDbrow);
		return d == null ? Double.NaN : d;
	}

	private Map<Integer, Double> shortestFrom(int source)
	{
		Map<Integer, Double> cached = shortest.get(source);
		if (cached != null)
		{
			return cached;
		}
		if (port(source) == null)
		{
			return null;
		}
		Map<Integer, List<double[]>> adj = new HashMap<>();
		for (Route r : routes)
		{
			adj.computeIfAbsent(r.a, k -> new ArrayList<>()).add(new double[]{r.b, r.distance});
			adj.computeIfAbsent(r.b, k -> new ArrayList<>()).add(new double[]{r.a, r.distance});
		}
		Map<Integer, Double> dist = new HashMap<>();
		dist.put(source, 0.0);
		PriorityQueue<double[]> queue = new PriorityQueue<>((x, y) -> Double.compare(x[1], y[1]));
		queue.add(new double[]{source, 0});
		while (!queue.isEmpty())
		{
			double[] cur = queue.poll();
			int at = (int) cur[0];
			if (cur[1] > dist.getOrDefault(at, Double.MAX_VALUE))
			{
				continue;
			}
			for (double[] edge : adj.getOrDefault(at, List.of()))
			{
				int next = (int) edge[0];
				double nd = cur[1] + edge[1];
				if (nd < dist.getOrDefault(next, Double.MAX_VALUE))
				{
					dist.put(next, nd);
					queue.add(new double[]{next, nd});
				}
			}
		}
		shortest.put(source, dist);
		return dist;
	}

	public static class Port
	{
		public int dbrow;
		public String name;
		public Integer level;   // Sailing level to dock; null = unstated
		public int x;
		public int y;
		public int plane;
		public boolean board;   // has a task noticeboard
	}

	public static class Reward
	{
		public int dbrow;
		public int xp;          // Sailing XP for completing the task
		public String label;    // the reference's comment ("Catherby grog delivery")
		public String type;     // courier | bounty
	}

	public static class Route
	{
		public int a;           // port dbrow
		public int b;           // port dbrow
		public double distance; // tiles along the reference's sailing path
	}
}
