package com.ironhub.data;

import java.util.List;
import java.util.Map;

/**
 * Quest actions for the goal engine (data/quests.json): per quest its
 * requirement expressions, official-length minutes, quest points, xp
 * rewards and position on the community ironman route (the router's
 * ordering prior). Generated by tools/gen_quests.py from the wiki —
 * never hand-edit.
 */
public class QuestsPack
{
	public String source;
	public String generated;
	public List<QuestEntry> quests;

	public QuestEntry byName(String name)
	{
		return quests.stream().filter(q -> q.name.equalsIgnoreCase(name)).findFirst().orElse(null);
	}

	public static class QuestEntry
	{
		public String name;
		/** RuneLite Quest enum display name; null = undetectable (manual). */
		public String enumName;
		public int minutes;
		public int qp;
		/** Position on the Optimal Quest Guide/Ironman route, -1 if absent. */
		public int order;
		public List<String> reqs;
		/** Xp rewards by skill display name. */
		public Map<String, Integer> xp;
	}
}
