package com.ironhub.data;

import java.util.List;
import java.util.Map;

/**
 * Quest actions for the goal engine (data/quests.json): per quest its
 * requirement expressions, official-length minutes, quest points, xp
 * rewards and position on the community ironman route (the router's
 * ordering prior). Generated by tools/gen_quests.py from the wiki —
 * never hand-edit.
 */
public class QuestsPack
{
	public String source;
	public String generated;
	public List<QuestEntry> quests;

	/** The package's standard lazy index — byName used to be a linear
	 *  stream scan, and QuestsTab called it per enum entry AND per sort
	 *  comparison, per keystroke (2026-07-20 audit). */
	private transient volatile Map<String, QuestEntry> byName;

	public QuestEntry byName(String name)
	{
		Map<String, QuestEntry> index = byName;
		if (index == null)
		{
			index = new java.util.HashMap<>();
			for (QuestEntry quest : quests)
			{
				index.put(quest.name.toLowerCase(java.util.Locale.ROOT), quest);
			}
			byName = index;
		}
		return index.get(name.toLowerCase(java.util.Locale.ROOT));
	}

	public static class QuestEntry
	{
		public String name;
		/** RuneLite Quest enum display name; null = undetectable (manual). */
		public String enumName;
		public int minutes;
		public int qp;
		/** Position on the Optimal Quest Guide/Ironman route, -1 if absent. */
		public int order;
		public List<String> reqs;
		/** Official difficulty (Novice..Grandmaster, Special for RFD parts);
		 *  null for miniquests and unrated entries. */
		public String difficulty;
		/** True for miniquests (no QP, no difficulty, no cape requirement). */
		public Boolean miniquest;
		/** Xp rewards by skill display name. */
		public Map<String, Integer> xp;
	}
}
