package com.ironhub.data;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Item production recipes (data/recipes.json, generated by tools/gen_recipes.py
 * from the OSRS wiki's {@code {{Recipe}}} templates). Goals v2: a supply Route
 * decomposes its stocked item to the raw materials you must gather.
 *
 * <p>The pack stores DIRECT recipes (one level each); {@link #decompose} walks
 * them to raw leaves — an item with no recipe is a leaf, and cycles are broken.
 * "Full raw" per Luke: refining steps (ore→bar, essence→rune, uncut→cut) are
 * followed too, so an ironman sees every gathered input.
 */
public class RecipesPack
{
	public String source;
	public String generated;
	public int version;
	/** output item id (string key) → its canonical recipe. */
	public Map<String, Recipe> recipes;

	public static class Recipe
	{
		public String name;
		public int outputQty = 1;
		public List<Material> materials;
	}

	public static class Material
	{
		public int itemId;
		public int qty;
		public String name;
	}

	/** This item's direct recipe, or null when it has none (a raw leaf). */
	public Recipe recipe(int itemId)
	{
		return recipes == null ? null : recipes.get(String.valueOf(itemId));
	}

	/**
	 * Fully decompose {@code qty} of an item to its raw-material leaves
	 * (item id → total quantity), insertion-ordered by first appearance.
	 * An item with no recipe is a leaf; a recipe outputting N per make scales
	 * the demand by {@code ceil}. Cycles (an item reachable from itself) stop
	 * at the repeat so the walk always terminates.
	 */
	public Map<Integer, Integer> decompose(int itemId, int qty)
	{
		Map<Integer, Integer> out = new LinkedHashMap<>();
		accumulate(itemId, qty, out, new java.util.HashSet<>());
		return out;
	}

	private void accumulate(int itemId, long qty, Map<Integer, Integer> out, java.util.Set<Integer> path)
	{
		Recipe r = recipe(itemId);
		if (r == null || r.materials == null || r.materials.isEmpty() || !path.add(itemId))
		{
			out.merge(itemId, (int) Math.min(Integer.MAX_VALUE, qty), Integer::sum);
			return;
		}
		int per = Math.max(1, r.outputQty);
		long makes = (qty + per - 1) / per; // ceil
		for (Material m : r.materials)
		{
			accumulate(m.itemId, makes * Math.max(1, m.qty), out, path);
		}
		path.remove(itemId);
	}

	/**
	 * What you actually need to GATHER for {@code qty} of an item, given what
	 * you already own (Luke): walk the recipe backwards, and at every node
	 * spend the owned stock first — a node fully covered by the bank stops
	 * there (its own materials are never gathered), and only the shortfall
	 * decomposes further. So 100 games necklaces when you hold the gold bars,
	 * sapphires and cosmics needs nothing gathered, not their raw ores.
	 *
	 * @param ownedCount item id → how many are on hand (bank + carried)
	 */
	public Map<Integer, Integer> gather(int itemId, int qty, java.util.function.IntUnaryOperator ownedCount)
	{
		Map<Integer, Integer> out = new LinkedHashMap<>();
		gather(itemId, qty, ownedCount, new java.util.HashMap<>(), out, new java.util.HashSet<>());
		return out;
	}

	private void gather(int itemId, long qty, java.util.function.IntUnaryOperator ownedCount,
		Map<Integer, Integer> spent, Map<Integer, Integer> out, java.util.Set<Integer> path)
	{
		// spend what we own of THIS item first (tracked so a bank stack isn't
		// double-counted across sibling branches)
		long have = Math.max(0, (long) ownedCount.applyAsInt(itemId) - spent.getOrDefault(itemId, 0));
		long use = Math.min(qty, have);
		if (use > 0)
		{
			spent.merge(itemId, (int) use, Integer::sum);
		}
		long remaining = qty - use;
		if (remaining <= 0)
		{
			return; // the bank covers it — nothing to gather down this branch
		}
		Recipe r = recipe(itemId);
		if (r == null || r.materials == null || r.materials.isEmpty() || !path.add(itemId))
		{
			out.merge(itemId, (int) Math.min(Integer.MAX_VALUE, remaining), Integer::sum);
			return;
		}
		int per = Math.max(1, r.outputQty);
		long makes = (remaining + per - 1) / per; // ceil
		for (Material m : r.materials)
		{
			gather(m.itemId, makes * Math.max(1, m.qty), ownedCount, spent, out, path);
		}
		path.remove(itemId);
	}

	/** A display name for an item that appears anywhere in the pack (as an
	 *  output or a material), or null. Built lazily. */
	public String name(int itemId)
	{
		if (names == null)
		{
			Map<Integer, String> built = new java.util.HashMap<>();
			if (recipes != null)
			{
				for (Map.Entry<String, Recipe> e : recipes.entrySet())
				{
					try
					{
						built.putIfAbsent(Integer.parseInt(e.getKey()), e.getValue().name);
					}
					catch (NumberFormatException ignored)
					{
						// non-numeric key can't be an item id — skip
					}
					if (e.getValue().materials != null)
					{
						for (Material m : e.getValue().materials)
						{
							built.putIfAbsent(m.itemId, m.name);
						}
					}
				}
			}
			names = built;
		}
		return names.get(itemId);
	}

	private transient volatile Map<Integer, String> names;
}
