package com.ironhub.data;

import java.util.List;
import java.util.Map;

/**
 * What each skill level unlocks (data/skill-unlocks.json, generated by
 * tools/gen_skill_unlocks.py from the wiki's "&lt;Skill&gt;/Level up table"
 * pages). Ships Farming and Herblore — the farm-runs sidebar says what the
 * next level of each is worth.
 */
public class SkillUnlocksPack
{
	public String source;
	public String generated;
	/** skill name → level (string key) → unlock lines. */
	public Map<String, Map<String, List<String>>> skills;

	/** Unlock lines for a skill at a level, or an empty list. */
	public List<String> unlocks(String skill, int level)
	{
		Map<String, List<String>> levels = skills == null ? null : skills.get(skill);
		List<String> lines = levels == null ? null : levels.get(String.valueOf(level));
		return lines == null ? List.of() : lines;
	}
}
