package com.ironhub.data;

import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import net.runelite.api.coords.WorldPoint;

/**
 * Slayer suite pack (data/slayer-tasks.json, generated by
 * tools/gen_slayer.py): the task catalog (canonical names + NPC target
 * names from core's Task.java at the pinned RuneLite tag, monster stats
 * from the wiki's Bucket API, locations/bring lists from Slayer Simplified,
 * Turael-skipping spots from Turael Skipping — all BSD-2), the nine master
 * assignment tables from the wiki, and the Slayer Rewards point unlocks
 * joined to gameval VarbitID constant names.
 */
public class SlayerTasksPack
{
	public int version;
	public List<Task> tasks;
	public List<Master> masters;
	public List<Unlock> unlocks;

	private transient volatile Map<String, Task> byName;

	/** Task by canonical name, case-insensitive; null when unknown. */
	public Task task(String name)
	{
		if (byName == null)
		{
			Map<String, Task> m = new HashMap<>();
			for (Task t : tasks)
			{
				m.put(t.name.toLowerCase(Locale.ROOT), t);
			}
			byName = m;
		}
		return name == null ? null : byName.get(name.toLowerCase(Locale.ROOT));
	}

	/** Master by focus id (VarbitID.SLAYER_MASTER value), or null. */
	public Master masterByFocus(int focusId)
	{
		for (Master m : masters)
		{
			if (m.focusId == focusId)
			{
				return m;
			}
		}
		return null;
	}

	/** Master whose name or dialog alias matches, case-insensitive. */
	public Master masterByName(String name)
	{
		if (name == null)
		{
			return null;
		}
		for (Master m : masters)
		{
			if (m.name.equalsIgnoreCase(name))
			{
				return m;
			}
			if (m.aliases != null)
			{
				for (String alias : m.aliases)
				{
					if (alias.equalsIgnoreCase(name))
					{
						return m;
					}
				}
			}
		}
		return null;
	}

	public static class Task
	{
		public String name;
		public int icon;
		public List<String> targets;
		public Finisher finisher;
		/** Requirement-graph strings, allOf semantics (empty/null = open). */
		public List<String> reqs;
		public Stats stats;
		public List<Location> locations;
		public List<BringItem> bring;
		public Turael turael;
	}

	public static class Finisher
	{
		public int itemId;
		public int threshold;
	}

	public static class Stats
	{
		public Integer level;
		public Integer hp;
		public Integer maxHit;
		public String attackStyle;
		public Integer attackSpeed;
		public Integer defStab;
		public Integer defSlash;
		public Integer defCrush;
		public Integer defMagic;
		public Integer defRanged;
		public String weakness;
		public Integer weaknessPercent;
		public Integer slayerLevel;
		public Double slayerXp;
		public List<String> attributes;
		public Boolean cannonImmune;
		public Boolean poisonous;
	}

	public static class Location
	{
		public String name;
		public Integer x;
		public Integer y;
		public Integer plane;
		public List<String> reqs;

		/** Routable world point, or null when the pack has no coordinates. */
		public WorldPoint worldPoint()
		{
			return x == null || y == null ? null
				: new WorldPoint(x, y, plane == null ? 0 : plane);
		}
	}

	public static class BringItem
	{
		public String name;
		public boolean required;
		public Integer id;
	}

	public static class Turael
	{
		public List<Integer> point; // x, y, plane — the Shortest Path target
		public String note;
		public List<TuraelLocation> locations;

		public WorldPoint worldPoint()
		{
			return point == null || point.size() < 3 ? null
				: new WorldPoint(point.get(0), point.get(1), point.get(2));
		}
	}

	public static class TuraelLocation
	{
		public String name;
		public List<String> teleports;
		/** Kill-area rectangles as [x1, y1, x2, y2, plane], inclusive corners. */
		public List<List<Integer>> areas;
	}

	public static class Master
	{
		public String name;
		public int focusId;
		public int x;
		public int y;
		public int plane;
		public int points;
		public boolean wilderness;
		public List<String> reqs;
		public List<String> aliases;
		public List<Assignment> tasks;

		public WorldPoint worldPoint()
		{
			return new WorldPoint(x, y, plane);
		}

		/** This master's row for a task (case-insensitive), or null. */
		public Assignment assignment(String taskName)
		{
			if (taskName == null)
			{
				return null;
			}
			for (Assignment a : tasks)
			{
				if (a.task.equalsIgnoreCase(taskName))
				{
					return a;
				}
			}
			return null;
		}
	}

	public static class Assignment
	{
		public String task; // canonical lower-case catalog name
		public int weight;
		public String amount;
		public String extended;
		public List<String> reqs;
		public List<String> locations; // Konar's location-locked lists
	}

	public static class Unlock
	{
		public String key;     // unlock:<key> requirement-graph flag
		public String name;
		public int points;
		public String varbit;  // gameval VarbitID constant name
		public String category; // unlock | extend
		public String desc;
	}
}
