package com.ironhub.data;

import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The Supplies runway catalog (data/supplies.json, generated by
 * tools/gen_supplies.py): consumables and resources an ironman stocks,
 * grouped into a handful of categories. Each category carries a curated
 * top-20 "most useful" default (shown until the player edits their list)
 * and a broader searchable membership.
 *
 * <p>The catalog is positively sourced (the knowledge-base consumables
 * table + curated resource families), so it contains no equipment — a
 * weapon can never appear here, which is the bug the old consumption-log
 * list had.
 */
public class SuppliesPack
{
	public String source;
	public List<Category> categories;
	public List<Item> items;

	public static class Category
	{
		public String key;
		public String name;
		/** Item id whose sprite is the category tile's icon. */
		public int icon;
	}

	public static class Item
	{
		public int id;
		public String name;
		public String category;
		/** True for the curated top-20 shown by default; absent = search-only. */
		@SerializedName("default")
		public Boolean isDefault;
	}

	// lazy indexes — volatile because the pack instance is shared across threads
	private volatile Map<Integer, Item> byId;
	private volatile Map<String, Category> byKey;

	private Map<Integer, Item> byId()
	{
		Map<Integer, Item> local = byId;
		if (local == null)
		{
			local = new ConcurrentHashMap<>();
			for (Item item : items)
			{
				local.putIfAbsent(item.id, item);
			}
			byId = local;
		}
		return local;
	}

	private Map<String, Category> byKey()
	{
		Map<String, Category> local = byKey;
		if (local == null)
		{
			local = new ConcurrentHashMap<>();
			for (Category c : categories)
			{
				local.putIfAbsent(c.key, c);
			}
			byKey = local;
		}
		return local;
	}

	/** The catalog entry for an item id, or null if it is not a tracked supply. */
	public Item item(int id)
	{
		return byId().get(id);
	}

	public Category category(String key)
	{
		return byKey().get(key);
	}

	/** Every catalog item in a category, in pack order (defaults first). */
	public List<Item> inCategory(String key)
	{
		List<Item> out = new ArrayList<>();
		for (Item item : items)
		{
			if (item.category.equals(key))
			{
				out.add(item);
			}
		}
		return out;
	}

	/** The curated default item ids for a category (the top-20). */
	public List<Integer> defaultIds(String key)
	{
		List<Integer> out = new ArrayList<>();
		for (Item item : items)
		{
			if (item.category.equals(key) && Boolean.TRUE.equals(item.isDefault))
			{
				out.add(item.id);
			}
		}
		return out;
	}

	/**
	 * Catalog items whose name contains the query (case-insensitive),
	 * across every category — this is what "search for any consumable or
	 * resource to add" lists. Empty query returns nothing.
	 */
	public List<Item> search(String query)
	{
		List<Item> out = new ArrayList<>();
		if (query == null)
		{
			return out;
		}
		String q = query.trim().toLowerCase(Locale.ROOT);
		if (q.isEmpty())
		{
			return out;
		}
		for (Item item : items)
		{
			if (item.name.toLowerCase(Locale.ROOT).contains(q))
			{
				out.add(item);
			}
		}
		return out;
	}
}
