package com.ironhub.data;

import java.util.List;
import java.util.Locale;

/**
 * Per-action xp fingerprints (data/xp-actions.json, generated by
 * tools/gen_xp_actions.py from the wiki's Module:Skill calc Lua data):
 * the exact xp one action awards — one xp drop. The planner overlay
 * matches the player's observed median drop against these to name the
 * training method actually in use.
 */
public class XpActionsPack
{
	public String source;
	public String generated;
	public List<SkillActions> skills;

	public SkillActions ladder(net.runelite.api.Skill skill)
	{
		String wanted = skill.getName().toLowerCase(Locale.ROOT);
		return skills.stream()
			.filter(l -> l.skill.toLowerCase(Locale.ROOT).equals(wanted))
			.findFirst()
			.orElse(null);
	}

	public static class SkillActions
	{
		public String skill;
		public List<XpAction> actions;
	}

	public static class XpAction
	{
		public String name;
		public int level;
		public double xp;
		public String type;
	}
}
