#!/usr/bin/env python3
"""Vendor RuneLite core's Time Tracking engine into com.ironhub.modules.farming.rl.

Iron Hub's farming module is a READ-ONLY consumer of the core Time Tracking
plugin's persisted data (config group "timetracking", RSProfile-scoped:
"<regionID>.<varbit>=<value>:<unixtime>" per patch, "birdhouse.<varp>" per
bird house space, plus the learned farming-tick offset). The core plugin —
enabled by default in RuneLite — stays the single writer; we vendor its
decode/predict machinery so we can interpret that data ourselves.

This mirrors the hub-approved Time Tracking Reminder plugin's update.js
(github.com/queicherius/runelite-time-tracking-reminder, BSD-2): copy the
farming + hunter packages from the RuneLite tag matching our client
dependency, rename packages, strip Guice annotations, widen visibility,
remove every config WRITE, and regroup PatchImplementation onto a finer
Tab enum (one category per infobox-worthy patch type).

Skipped files (core Swing panels, or hand-ported): FarmingTracker (a
trimmed read-only port lives in rl/ as a hand-maintained file),
FarmingTabPanel, FarmingNextTickPanel, FarmingContractInfoBox,
BirdHouseTabPanel.

TimetrackingParityTest sweeps the vendored decode against the classpath
client's PatchImplementation — when the client dependency moves past this
tag in a breaking way, CI fails and this script must be re-run with the
new tag.

Usage:
  python3 tools/gen_timetracking.py [tag]     # default TAG below

Fetches from raw.githubusercontent.com, cached under
tools/.cache-timetracking/ (gitignored).
"""
import os
import re
import sys
import urllib.request

TAG = "runelite-parent-1.12.32"  # keep in lockstep with the resolved net.runelite:client version
BASE = ("https://raw.githubusercontent.com/runelite/runelite/{tag}/"
        "runelite-client/src/main/java/net/runelite/client/plugins/timetracking/")
UA = "IronHub RuneLite plugin data generator (github.com/ellismosss/iron-hub; info@ellismoss.co.uk)"
CACHE = os.path.join(os.path.dirname(__file__), ".cache-timetracking")
OUT_DIR = "src/main/java/com/ironhub/modules/farming/rl"

FARMING_FILES = [
    "Autoweed", "CompostState", "CompostTracker", "CropState",
    "FarmingContractManager", "FarmingPatch", "FarmingRegion", "FarmingWorld",
    "PatchImplementation", "PatchPrediction", "PatchState", "PaymentTracker",
    "Produce", "ProfilePatch",
]
HUNTER_FILES = [
    "BirdHouse", "BirdHouseData", "BirdHouseSpace", "BirdHouseState",
    "BirdHouseTracker",
]

GENERATED = ("// THIS FILE WAS GENERATED BY tools/gen_timetracking.py FROM RUNELITE {tag}.\n"
             "// DO NOT EDIT MANUALLY — regenerate when the client dependency moves.\n\n")

# PatchImplementation entries regrouped onto the finer Tab (one category per
# infobox-worthy type) — the Time Tracking Reminder plugin's mapping.
TAB_REWRITES = [
    ("HESPORI(Tab.SPECIAL,", "HESPORI(Tab.HESPORI,"),
    ("HARDWOOD_TREE(Tab.TREE,", "HARDWOOD_TREE(Tab.HARDWOOD,"),
    ("REDWOOD(Tab.TREE,", "REDWOOD(Tab.REDWOOD,"),
    ("SPIRIT_TREE(Tab.TREE, ", "SPIRIT_TREE(Tab.SPECIAL, "),
    ("CACTUS(Tab.SPECIAL, ", "CACTUS(Tab.CACTUS, "),
    ("SEAWEED(Tab.SPECIAL,", "SEAWEED(Tab.SEAWEED,"),
    ("CALQUAT(Tab.FRUIT_TREE,", "CALQUAT(Tab.CALQUAT,"),
    ("CELASTRUS(Tab.FRUIT_TREE,", "CELASTRUS(Tab.CELASTRUS,"),
    ("CRYSTAL_TREE(Tab.FRUIT_TREE, ", "CRYSTAL_TREE(Tab.CRYSTAL, "),
    ("BIG_COMPOST(Tab.SPECIAL,", "BIG_COMPOST(Tab.BIG_COMPOST,"),
    ("BELLADONNA(Tab.SPECIAL,", "BELLADONNA(Tab.BELLADONNA,"),
    ("MUSHROOM(Tab.SPECIAL,", "MUSHROOM(Tab.MUSHROOM,"),
    ("CORAL(Tab.SPECIAL,", "CORAL(Tab.CORAL,"),
]

CONTRACT_MANAGER_CTOR = """\tpublic FarmingContractManager(Client client, ItemManager itemManager, ConfigManager configManager, TimeTrackingConfig config, FarmingWorld farmingWorld, FarmingTracker farmingTracker)
\t{
\t\tthis.client = client;
\t\tthis.itemManager = itemManager;
\t\tthis.configManager = configManager;
\t\tthis.config = config;
\t\tthis.farmingWorld = farmingWorld;
\t\tthis.farmingTracker = farmingTracker;
\t}

"""


def fetch(tag: str, sub: str, name: str) -> str:
    os.makedirs(CACHE, exist_ok=True)
    cached = os.path.join(CACHE, f"{tag}-{sub}-{name}.java")
    if not os.path.exists(cached):
        url = BASE.format(tag=tag) + f"{sub}/{name}.java"
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req) as resp:
            body = resp.read().decode("utf-8")
        with open(cached, "w", encoding="utf-8") as f:
            f.write(body)
    with open(cached, encoding="utf-8") as f:
        return f.read()


def patch(content: str, name: str, tag: str) -> str:
    # package + cross-package imports
    content = content.replace(
        "package net.runelite.client.plugins.timetracking.farming;",
        "package com.ironhub.modules.farming.rl;")
    content = content.replace(
        "package net.runelite.client.plugins.timetracking.hunter;",
        "package com.ironhub.modules.farming.rl.hunter;")
    content = content.replace(
        "import net.runelite.client.plugins.timetracking.farming.", "import com.ironhub.modules.farming.rl.")
    # our finer Tab lives in the rl package — same package for farming files
    content = content.replace("import net.runelite.client.plugins.timetracking.Tab;\n", "")
    # SummaryState + TimeTrackingConfig are public core API — their imports stay.

    # Guice annotations (we construct everything by hand)
    content = re.sub(r"\t*@Inject\n", "", content)
    content = re.sub(r"\t*@Singleton\n", "", content)

    # visibility (update.js recipe)
    content = re.sub(r"access = AccessLevel\.PACKAGE,?", "", content)
    content = re.sub(r"access = AccessLevel\.PRIVATE,?", "", content)
    content = content.replace("private BirdHouseTracker(", "public BirdHouseTracker(")
    content = content.replace("private void updateCompletionTime", "public void updateCompletionTime")
    content = content.replace("class FarmingWorld", "public class FarmingWorld")
    content = content.replace("\tFarmingWorld(", "\tpublic FarmingWorld(")
    content = content.replace("private void handleContractState", "public void handleContractState")
    content = content.replace("class FarmingPatch", "public class FarmingPatch")
    content = content.replace("class PatchPrediction", "public class PatchPrediction")
    content = content.replace("class PatchState", "public class PatchState")
    content = content.replace("\tFarmingRegion(", "\tpublic FarmingRegion(")

    # Iron Hub's consumers live OUTSIDE the rl package (unlike core, where
    # the plugin shares it) — widen the remaining package-private surface.
    content = re.sub(r"^enum ", "public enum ", content, flags=re.MULTILINE)
    content = re.sub(r"^class ", "public class ", content, flags=re.MULTILINE)
    content = content.replace("\tabstract PatchState forVarbitValue",
        "\tpublic abstract PatchState forVarbitValue")
    content = content.replace("\t\t\tPatchState forVarbitValue(int value)",
        "\t\t\tpublic PatchState forVarbitValue(int value)")
    content = content.replace("\tint getStages()", "\tpublic int getStages()")
    content = content.replace("\tint getTickRate()", "\tpublic int getTickRate()")
    content = content.replace("\tCollection<FarmingRegion> getRegionsForLocation(",
        "\tpublic Collection<FarmingRegion> getRegionsForLocation(")

    if name == "FarmingContractManager":
        content = content.replace("\tpublic void setContract",
            CONTRACT_MANAGER_CTOR + "\tpublic void setContract")

    if name == "FarmingContractManager":
        # Strip the core-UI infobox machinery — Iron Hub renders its own
        # contract status; the vendored manager only tracks state.
        content = content.replace("import net.runelite.client.plugins.timetracking.TimeTrackingPlugin;\n", "")
        content = content.replace("import net.runelite.client.ui.overlay.infobox.InfoBoxManager;\n", "")
        content = re.sub(r"\tprivate TimeTrackingPlugin plugin;\n\n", "", content)
        content = re.sub(r"\tprivate InfoBoxManager infoBoxManager;\n\n", "", content)
        content = re.sub(r"\t@Getter\n\t@Setter\n\tprivate FarmingContractInfoBox infoBox;\n\n", "", content)
        content = re.sub(
            r"\t*private void handleInfoBox\(\)\n\t\{\n(?:.*\n)*?\t\}\n\n", "", content)
        content = content.replace("\t\t\thandleInfoBox();\n", "")
        content = re.sub(
            r"\t\telse\n\t\t\{\n\t\t\tif \(infoBox != null\)\n\t\t\t\{\n"
            r"\t\t\t\tinfoBoxManager\.removeInfoBox\(infoBox\);\n"
            r"\t\t\t\tinfoBox = null;\n\t\t\t\}\n\t\t\}\n", "", content)

    if name == "PatchImplementation":
        for old, new in TAB_REWRITES:
            if old not in content:
                raise SystemExit(f"Tab rewrite no longer matches: {old!r} — re-check against {tag}")
            content = content.replace(old, new)

    if name == "BirdHouseTracker":
        # drop the core-UI factory method (we don't vendor BirdHouseTabPanel)
        content = re.sub(
            r"\tpublic BirdHouseTabPanel createBirdHouseTabPanel\(\)\n\t\{\n(?:.*\n)*?\t\}\n\n",
            "", content)

    # READ-ONLY: the core plugin is the single writer of the timetracking group
    content = re.sub(
        r"configManager\.setRSProfileConfiguration\(.*?\);",
        "// config write removed: Iron Hub reads the core Time Tracking plugin's data, never writes it.",
        content, flags=re.DOTALL)
    content = re.sub(
        r"configManager\.unsetRSProfileConfiguration\(.*?\);",
        "// config write removed: Iron Hub reads the core Time Tracking plugin's data, never writes it.",
        content, flags=re.DOTALL)

    header = GENERATED.format(tag=tag)
    content = content.replace("/*\n * Copyright", header + "/*\n * Copyright", 1)
    return content


def main():
    tag = sys.argv[1] if len(sys.argv) > 1 else TAG
    os.makedirs(f"{OUT_DIR}/hunter", exist_ok=True)
    written = []
    for name in FARMING_FILES:
        content = patch(fetch(tag, "farming", name), name, tag)
        path = f"{OUT_DIR}/{name}.java"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)
    for name in HUNTER_FILES:
        content = patch(fetch(tag, "hunter", name), name, tag)
        path = f"{OUT_DIR}/hunter/{name}.java"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)
    print(f"wrote {len(written)} files from {tag} into {OUT_DIR}")
    leftovers = [p for p in written if "setRSProfileConfiguration" in open(p).read()]
    if leftovers:
        raise SystemExit(f"config writes survived in: {leftovers}")


if __name__ == "__main__":
    main()
